# Jus for basic configuration for local enviornment variables
ATLAS_HOST_NAME: missingchildrenukraine.nzlsq.mongodb.net
MONGO_USER: AiClub
MONGO_PASSWORD: 13MissingChild_69
MONGO_DATABASE: MissingChildrenUkraine
